# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Maurizio Monti
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a scientist working on ultrafast spectroscopy of condensed matter. Here will find info on my research, papers and projects.
domain: "mmonti92.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmonti92.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: mauri_monti
#linkedin_username: maurizio-monti
#github_username:  mmonti92

header_pages:
  - about.markdown
  - Research.md
  - Publications.md
  - Contact.md

timezone: Europe/Paris

# Build settings
#theme: minima
remote_theme:  jekyll/minima
#remote_theme: https://github.com/pages-themes/midnight
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  #- jekyll-include-cache


# Collections
#collections:
 # research_item:
 #   output: true
collections:
  publications:
    output: true
    permalink: /:collection/:name
  preprints:
    output: true
    permalink: /:collection/:name



minima:
  skin: dark
  social_links:
    - title: Google scholar
      icon: google-scholar
      url: "https://scholar.google.com/citations?user=3XhkV98AAAAJ&hl=en"
    - title: OrcID
      icon: orcid
      url: "https://orcid.org/my-orcid?orcid=0000-0003-2192-3747"
    - title: Researchgate
      icon: researchgate
      url: https://www.researchgate.net/profile/Maurizio-Monti?ev=hdr_xprf
    - title: GitHub repository
      icon: github
      url: "https://github.com/mmonti92"
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/maurizio-monti/"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
